import React from 'react';
import { View, ScrollView } from 'react-native';
import { Container } from '@components/layout/container';
import { useAuthStore } from '@stores/auth.store';
import { Text } from '@components/ui/text';
import { SettingRow } from '@components/common/setting-row';
import { ProfileDetailRow } from '../components/profile-detail-row';
import { ConfirmLogoutAlert, ProfileScreenSkeleton } from '../components';
import { useProfileSections } from '../hooks/use-profile-sections';
import { Card, CardHeader, CardContent } from '@components/ui/card';
import { GovtHeader } from '@components/common/govt-header';
import { useProfile } from '../hooks';
import { EmptyScreen } from '@components/screens';

/**
 * Profile screen that displays the logged-in user's employment, pay, PF,
 * GIS, and bank details in NIC portal-style section cards.
 *
 * Handles three states:
 * - **Loading**: Renders a {@link ProfileScreenSkeleton} with shimmer
 *   placeholders while the profile query is fetching.
 * - **Empty / Error**: If the profile data is null after loading, shows
 *   an {@link EmptyScreen} with a refresh action.
 * - **Loaded**: Renders the full profile layout including:
 *   - `GovtHeader` with employee name, DDO info, and employee code
 *   - Section cards generated by {@link useProfileSections} (employee
 *     details, employment, pay, PF, GIS, bank)
 *   - A Preferences & Account settings card with change password,
 *     service record, and logout actions
 *   - App footer with version attribution
 *
 * @example
 * ```tsx
 * <ProfileScreen />
 * ```
 */
export const ProfileScreen = () => {
  const { emp_cd } = useAuthStore();
  const [showLogoutAlert, setShowLogoutAlert] = React.useState(false);
  const { data: profile, isLoading, refetch } = useProfile();
  const profileSections = useProfileSections(profile);

  if (isLoading) return <ProfileScreenSkeleton />;

  if (!profile)
    return (
      <EmptyScreen
        icon="person"
        refresh={refetch}
        refreshLabel="Refresh"
        title="Profile not found"
        message="Please try again"
      />
    );

  return (
    <Container>
      {/* Identity Header — Govt branding */}
      <View className="border-b border-border bg-background pb-4 pt-4">
        <GovtHeader
          title={profile ? `${profile.emp_fname} ${profile.emp_lname}` : 'Loading...'}
          subtitle={profile ? `Current DDO: ${profile.ddo_code} - ${profile.ddo_name}` : undefined}
          badge={emp_cd ? `Employee Code: ${emp_cd}` : '-'}
        />

        {/* Employee code inline when no badge */}
        {!emp_cd && (
          <Text variant="subtext" size="xs" className="text-center text-graphite">
            Employee Code: —
          </Text>
        )}
      </View>

      <ScrollView className="flex-1 pt-6" showsVerticalScrollIndicator={false}>
        {/* Profile sections rendered as NIC portal-style cards */}
        {profileSections.map((section) => (
          <Card key={section.title} variant="bordered" className="mb-4 overflow-hidden">
            {/* Section header */}
            <CardHeader className="bg-surface-soft px-4 py-2.5">
              <Text className="text-xs font-bold uppercase tracking-wider text-graphite">
                {section.title}
              </Text>
            </CardHeader>

            {/* Two-column table rows */}
            <CardContent className="p-0">
              {section.fields.map((field) => (
                <ProfileDetailRow
                  key={field.label}
                  label={field.label}
                  value={field.value || '-'}
                />
              ))}
            </CardContent>
          </Card>
        ))}

        {/* Settings */}
        <View className="mb-10">
          <Text
            variant="subtext"
            size="xs"
            className="mb-2 font-bold uppercase tracking-wider text-graphite">
            Preferences & Account
          </Text>
          <Card variant="bordered" className="px-2">
            <SettingRow icon="lock-closed-outline" label="Change Password" onPress={() => {}} />
            <SettingRow icon="document-text-outline" label="Service Record" onPress={() => {}} />
            <SettingRow
              icon="log-out-outline"
              label="Log Out"
              isDestructive
              onPress={() => setShowLogoutAlert(!showLogoutAlert)}
              showBorder={false}
            />
          </Card>
        </View>

        {/* Footer */}
        <View className="items-center pb-8 opacity-60">
          <Text variant="subtext" size="xs" className="text-graphite">
            NIC e-HRMS v2.0 • Government of India
          </Text>
        </View>
        <ConfirmLogoutAlert open={showLogoutAlert} onValueChange={setShowLogoutAlert} />
      </ScrollView>
    </Container>
  );
};
